### ISSUE TITLE
Cannot interact with SLI page, shows only white screen

### ISSUE THREAD

**Issue by mikemonk** [SchoolListit/SchoolListIt-Issues#27]
I am unable to use the app, as it only shows a white screen on login. I have tested this with both FireFox and Chrome, but only took screenshots of Firefox for this. I also tested it in incognito mode, and with ad-blockers disabled, but not for this test. 

- I login with Google SSO. I used my personal gmail in this case, but have tried both. 

- It logs me in, and I see the main interface (to search for a school, etc) for a very brief period of time (fast enough I couldn't get a screenshot) before it loads a white screen 

- I took screenshots, but nothing obvious (to me) appeared in the console. 
![1](https://user-images.githubusercontent.com/15092925/87310604-2f1d5980-c4ec-11ea-9867-e47c180a8244.PNG)
![4](https://user-images.githubusercontent.com/15092925/87310625-36dcfe00-c4ec-11ea-842f-a1e80d3a88fe.PNG)
![2](https://user-images.githubusercontent.com/15092925/87310626-36dcfe00-c4ec-11ea-98de-ae6c9cdf3c9b.PNG)
![3](https://user-images.githubusercontent.com/15092925/87310628-37759480-c4ec-11ea-8e13-dceff75e0105.PNG)

**Comment by megphillips91** [comment]
That is the error.... it is with my 'wizard landing page' I tried to change the way it worked with a 'quick fix' and created this bug. I've got to solve this important UI feature before the deadline for CFC!!!

**Comment by megphillips91** [comment]
Resolved - new login wizard
